name: build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build project

        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - uses: npm i